version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    container_name: onproc-backend
    networks:
      gisnet:
        aliases:
          - backend.gisnet

networks:
  gisnet:
    external: true